### ISSUE TITLE
Escrever o jogo ideal 

### ISSUE THREAD

**Issue by TheFBH** [Hairstyle-Company/SeguremOsPersas#2]
- [x] Descrição do universo;
- [x] Personagens;
- [x] Enredo / desenvolvimento da história

**Comment by Natanxtx** [comment]
O jogo se passa na Era Antiga, com o exército Grego de Esparta e o exército Persa protagonizando a batalha nas Termópilas. Os protagonistas do jogo são um Espartano chamado Apolo e um Térsio chamado Adônis.
A história se baseia no acontecimento real, porém com algumas alterações, sendo que no jogo, os únicos que sobraram do exército espartanos, são Apolo e Adônis que são soldados especiais que podem derrotar o exército persa desde que você conduza-os até o final.
